### ISSUE TITLE
Nonzero rotor speed at start-up

### ISSUE THREAD

**Issue by myusufc** [odtu/ee462#2]
Although I set all the initial conditions of the motor parameters to zero, and even the DC-Link capacitance and inductance, initial voltage and current values to zero, I get nonzero rotor speed at the start up. What is the reason, can you help me?

**Comment by UmutKilci** [comment]
I had the same issue. In the parameters section of the asynchronous machine, under initial conditions, first element is the initial slip. It should be 1 not zero. When I corrected, speed started from zero.
B.t.w. I am using R2015A version

**Comment by myusufc** [comment]
Thanks a lot 👍

**Comment by ozank** [comment]
:clap: :clap:
